# Review-Based Rating Construction

Background

Customer reviews often contain evaluations of several different parts of the purchasing experience within the same text. However, the dataset provides only a single overall customer rating for each review, which does not distinguish between evaluations of the product, seller, and delivery. A single review may, for example, praise the product while criticizing the delivery or the seller's responsiveness. To construct ratings for these different dimensions, the review must therefore first be decomposed into specific evaluative aspects.

In [15]:
import sys
from pathlib import Path

# Add the project root to Python's import path so modules in src/ can be imported.
PROJECT_ROOT = Path.cwd().parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

## Sentence Embedding for Aspect Candidate Discovery

Background

The later aspect-extraction step requires a predefined set of aspect categories. Rather than allowing the model to generate arbitrary aspect names, we first identify a manageable set of candidate aspects from the reviews themselves. This helps produce more consistent outputs and makes the extracted aspects easier to compare and aggregate later, particularly when evaluating different parts of the purchasing experience, such as the product, seller, and delivery.

To identify these candidates, we examine groups of reviews that are similar according to their sentence embeddings. Sentence embeddings represent each review as a fixed-length numerical vector, with reviews that are similar with respect to the embedding model's training objective tending to have similar representations. However, we do not assume that nearest neighbors are necessarily equivalent in meaning or that every review in a neighborhood expresses the same aspect.

Examining several related reviews together can make recurring themes easier to recognize than examining reviews in isolation. These recurring themes provide exploratory evidence that can then be used to manually select, consolidate, and define the candidate aspect categories for the subsequent extraction step.


### Methodology
This notebook samples 2,000 non-empty English reviews, converts them into sentence embeddings, and retrieves the eight nearest neighbors for each review. It provides functions for inspecting individual neighborhoods as well as a randomly selected set of neighborhoods.

The resulting groups of similar reviews are used as exploratory material for the subsequent manual identification and definition of candidate aspects. Random seeds are specified for the sampling procedures to make the inspection process reproducible.

In [2]:
import pandas as pd
import numpy as np
from transformers import AutoTokenizer, AutoModel
import torch

c:\Users\19148\anaconda3\envs\pydata-book\Lib\site-packages\requests\__init__.py:92: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(

### 1. Load the review data and construct a sample

This section loads the translated review dataset and constructs a fixed sample of 2,000 reviews containing non-empty English review comments. Reviews with missing or empty comments are removed before sampling, since they cannot provide useful information for sentence embedding or qualitative inspection.

Rather than embedding the entire table, we work with a fixed sample of 2,000 reviews. This keeps the exploratory analysis computationally manageable while still providing a sufficiently broad collection of reviews for inspecting recurring themes and potential aspect categories.

In [3]:
reviews = pd.read_csv(r"../src/reviews_translated.csv", index_col='order_id', 
                        parse_dates=['review_creation_date', 'review_answer_timestamp'], 
                        date_format="%Y-%m-%d %H:%M:%S")

sample = (
    reviews[
        reviews["review_comment_en"].notna() &
        reviews["review_comment_en"].str.strip().ne("")
    ]
    .sample(n=2000, random_state=42)
    .reset_index(drop=True)
)
texts = sample["review_comment_en"].tolist()

### 2. Load the embedding model

The all-MiniLM-L6-v2 model is used to transform each review into a dense vector representation that captures aspects of its semantic content. The model is loaded from the Hugging Face Hub using AutoTokenizer and AutoModel.

Because this notebook only uses the pretrained model to generate embeddings and does not perform any training or parameter updates, the model is placed in evaluation mode (`model.eval`), different from the training mode.

The computations are performed on a GPU when CUDA is available and otherwise fall back to the CPU. Moving the model to the selected device allows the subsequent embedding computation to use the available hardware.

In [4]:
model_name = "sentence-transformers/all-MiniLM-L6-v2"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

model.eval()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

print("Device:", device)

Device: cpu

### 3. Encode reviews as sentence embeddings

Each review is converted into a fixed-dimensional sentence embedding using the pretrained model loaded above. The resulting embedding represents each review as a numerical vector in a shared vector space. Reviews with similar semantic content are expected to have more similar embeddings, although embedding similarity does not guarantee that two reviews express exactly the same meaning or aspect.

Batch processing is used to reduce computational overhead, while a maximum sequence length of 128 tokens provides a practical limit for this exploratory analysis.Reviews longer than this limit are truncated.

`encode_sentences` handles the tokenization, model inference, pooling, and batching required to convert the review texts into embedding vectors.

In [5]:
from src.embeddings import encode_sentences

embeddings = encode_sentences(
    texts,
    tokenizer=tokenizer,
    model=model,
    device=device,
    batch_size=32,
    max_length=128
)

print(embeddings.shape)

torch.Size([2000, 384])

### 4. Compute semantic similarity and identify nearest neighbors

The pairwise similarity matrix is used to identify semantically similar reviews. Because the embeddings produced by the encoding function are normalized, their dot product is equivalent to cosine similarity. For each review, the eight reviews with the highest similarity scores are treated as its nearest neighbors.

A review is its own most similar item, so the diagonal of the similarity matrix is explicitly excluded before nearest-neighbor retrieval. Without this step, every review would trivially appear as its own first neighbor.

In [6]:
similarity = embeddings @ embeddings.T

k = 8

similarity_for_knn = similarity.clone()

# Exclude each review itself
similarity_for_knn.fill_diagonal_(-float("inf"))

# torch.topk retrieves k highest similarity scores and their review indices
neighbor_similarity, neighbor_indices = torch.topk(
    similarity_for_knn,
    k=k,
    dim=1
)

### 5. Inspect an individual review and its nearest neighbors

A single neighborhood is inspected first to verify that the nearest-neighbor retrieval behaves as expected. This provides a direct qualitative check of whether high similarity scores correspond to reviews with genuinely related content rather than merely sharing superficial vocabulary.

In [7]:
i = 2

print("Original review:")
print(sample.loc[i, "review_comment_en"])

print("\nNearest neighbors:")

for rank in range(k):

    j = neighbor_indices[i, rank].item()
    score = neighbor_similarity[i, rank].item()

    print(f"\n{rank + 1}. similarity = {score:.3f}")
    print(sample.loc[j, "review_comment_en"])

Original review:
The necklace is beautiful, with good finish on the pendants, the string of the necklace is good, the only part of the scapular that is not very well made are the rings to hang the pendants, came a bit crooked and open.

Nearest neighbors:

1. similarity = 0.642
I love the pendants, they're beautiful, well finished, of good quality.

2. similarity = 0.589
The shop itself is good but I asked for a necklace and came another completely different

3. similarity = 0.525
I got the defective pendant, broken.

4. similarity = 0.510
the pendants came peeling, one of them crushed and with the gold finish with defects.

5. similarity = 0.437
The chandelier is very beautiful, well finished, delicate painting. I recommend it!

6. similarity = 0.432
The watch itself is not so beautiful. It is very large and the material seems fragile for price. But the store delivered before and comes packed.

7. similarity = 0.429
Beautiful watch, very elegant, unbelievable in front of the value of less than R$ 150,00! It came very well wrapped and protected, outside it also has very chic box, as if it were jewelry!!!

8. similarity = 0.421
Product came without important piece to lock the pendant on the ceiling. I had to "turn" to get a similar piece that is not the same shown in the photo of the ad. I consider Propaganda Deceptive.

### 6. Encapsulate neighbor inspection in reusable functions

The `show_neighbors` function encapsulates the display logic for one review and its nearest neighbors. The number of neighbors shown is inferred directly from `neighbor_indices.shape[1]` rather than relying on the global k variable.

Separating presentation from the embedding and retrieval steps makes the notebook easier to read and allows the same inspection procedure to be reused for different reviews without duplicating code.

In [8]:
def show_neighbors(
    sample,
    neighbor_indices,
    neighbor_similarity,
    i,
    text_column="review_comment_en"
):
    """
    Display one review and its k nearest neighbors.
    """

    print("=" * 80)
    print(f"REVIEW {i}")
    print("=" * 80)

    print("\nOriginal:")
    print(sample.loc[i, text_column])

    print("\nNearest neighbors:")

    for rank in range(neighbor_indices.shape[1]):

        j = neighbor_indices[i, rank].item()
        score = neighbor_similarity[i, rank].item()

        print(f"\n{rank + 1}. similarity = {score:.3f}")
        print(sample.loc[j, text_column])

`inspect_random_neighbors` extends this procedure to multiple reviews. The sampling is performed without replacement, ensuring that the same review is not selected more than once within a single inspection.

In [9]:
def inspect_random_neighbors(
    sample,
    neighbor_indices,
    neighbor_similarity,
    n=10,
    text_column="review_comment_en",
    random_state=42
):
    rng = np.random.default_rng(random_state)

    indices = rng.choice(
        len(sample),
        size=n,
        replace=False
    )

    for i in indices:
        show_neighbors(
            sample,
            neighbor_indices,
            neighbor_similarity,
            i,
            text_column=text_column
        )

### 7. Apply the reusable KNN implementation

The get_knn function returns the k nearest neighbors and their cosine similarities for each embedding. It assumes that the embeddings are L2-normalized, so their dot products give cosine similarities, and each review is excluded from its own neighbors.

Here, we retrieve the eight nearest neighbors for all 2,000 reviews and inspect 20 randomly selected reviews. The resulting samples are then summarized manually to identify recurring topics that can be used to define candidate aspects.

In [10]:
from src.embeddings import get_knn

neighbors_8, similarities_8 = get_knn(
    embeddings,
    k=8
)

inspect_random_neighbors(
    sample,
    neighbors_8,
    similarities_8,
    n=20
)

================================================================================
REVIEW 1533
================================================================================

Original:
Satisfied with the product!

Nearest neighbors:

1. similarity = 0.845
I'm satisfied with the product.

2. similarity = 0.831
satisfied with the purchase made.

3. similarity = 0.788
Very satisfied with the purchase and the company!

4. similarity = 0.751
I'm satisfied with the purchase

5. similarity = 0.743
Satisfied!

6. similarity = 0.723
Satisfaction with the products and everything delivered in the right time. Thank you!

7. similarity = 0.718
Product received as announced. Customer satisfied.

8. similarity = 0.707
Very satisfied with the purchase and the service
================================================================================
REVIEW 1431
================================================================================

Original:
nice

Nearest neighbors:

1. similarity = 0.640
good

2. similarity = 0.640
good

3. similarity = 0.592
Very nice.

4. similarity = 0.592
Very nice.

5. similarity = 0.528
perfect

6. similarity = 0.503
Good.

7. similarity = 0.503
Good.

8. similarity = 0.503
Good.
================================================================================
REVIEW 400
================================================================================

Original:
Very nice.

Nearest neighbors:

1. similarity = 1.000
Very nice.

2. similarity = 0.731
Very beautiful.

3. similarity = 0.698
Very good.

4. similarity = 0.698
Very good.

5. similarity = 0.698
Very good.

6. similarity = 0.698
Very good.

7. similarity = 0.698
Very good.

8. similarity = 0.698
Very good.
================================================================================
REVIEW 1943
================================================================================

Original:
I haven't tested the product yet but the condition of the product is in perfect condition and there's no damage due to transport.

Nearest neighbors:

1. similarity = 0.559
The product came well packed, did not suffer any damage on the route. It came as I had chosen.

2. similarity = 0.507
The product presents risks, appearance of use, although it is working. The product was delivered in packaging, but wrapped in bubble paper, not packed in box.

3. similarity = 0.493
Product delivered on time in excellent conditions and without any problems.

4. similarity = 0.480
Let's wait to see product durability

5. similarity = 0.457
product very different from the divulged. super fragile.

6. similarity = 0.456
There was a breakdown in the packaging. The product went to another destination before this. The product photo does not match what I received. The product seems to work. I have not yet found an application to test.

7. similarity = 0.454
Very weak product, I wouldn't recommend it to anyone.

8. similarity = 0.443
Product was delivered within the deadline, surpassing my expectations. It came well packed and without damage, despite the box crushed.
================================================================================
REVIEW 1678
================================================================================

Original:
Very Luinda

Nearest neighbors:

1. similarity = 0.347
Very well attended

2. similarity = 0.347
Very well.

3. similarity = 0.340
Well served

4. similarity = 0.338
Super indian.

5. similarity = 0.329
Very delicate.

6. similarity = 0.323
Very satisfied

7. similarity = 0.323
Very satisfied

8. similarity = 0.319
within my expectations
================================================================================
REVIEW 1517
================================================================================

Original:
Product arrived within the deadline. Good product, well packed. However, the delivery time of the product was until 07/02, i.e. from 10/01, until 07/02, but arrived on 30/01.

Nearest neighbors:

1. similarity = 0.763
The product arrived outside the delivery deadline of 14/03 was delivered 15/03.

2. similarity = 0.749
The delivery was made before the deadline set by the store, I was very satisfied, the product is of quality.

3. similarity = 0.739
Product delivered within the deadline, well before the last scheduled day.

4. similarity = 0.737
product delivered before the expected date. was great

5. similarity = 0.735
Product arrived before deadline

6. similarity = 0.731
Product arrived well before the deadline set by the store.

7. similarity = 0.729
Product delivered well before the specified deadline

8. similarity = 0.729
Delivery is past deadline but the product has arrived!
================================================================================
REVIEW 255
================================================================================

Original:
I need to get in touch with you urgently.

Nearest neighbors:

1. similarity = 0.495
I bought two units, I only got one. I'd like you to get in touch with me.

2. similarity = 0.468
I need you to deliver the product to me.

3. similarity = 0.446
Good afternoon, so far I haven't received my purchase, and I've tried to get in touch with you, and I can't.

4. similarity = 0.412
Good night! I want you to get in touch with me.One chair arrived one day and yesterday another one arrived.

5. similarity = 0.411
My request arrived before the deadline and correctly. . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . .

6. similarity = 0.409
My product came different and has no email contact with someone to solve my problem, I am very sad with this purchase, mainly because I have no contact available as on the free market.

7. similarity = 0.399
The request arrived before the scheduled date, very satisfied

8. similarity = 0.375
not received
================================================================================
REVIEW 176
================================================================================

Original:
The product arrived in time, and with all the pieces, but some came with the pied or very dried bristles, and some brushes are very repeated. Apart from that the product is good

Nearest neighbors:

1. similarity = 0.576
I loved good mt product, not all are natural bristles brushes plus most eh. I loved high quality the bristles to love

2. similarity = 0.552
The brushes are beautiful and of great quality.

3. similarity = 0.541
The brushes are beautiful!!!!!!

4. similarity = 0.525
I bought a brush more than a month ago. They never posted.

5. similarity = 0.443
I received until today only one product that was the enamel bag. But the enamels that were bought together with the bag have not yet come.Would you like to know why?

6. similarity = 0.422
Didn't I get all the product?

7. similarity = 0.419
The product arrived in order and on the right day.

8. similarity = 0.415
The image of the product was included the trimmer, but came only the machine with the other parts without the trimmer.
================================================================================
REVIEW 1298
================================================================================

Original:
excellent and fast

Nearest neighbors:

1. similarity = 0.742
Very fast.

2. similarity = 0.681
Very good Fast delivery

3. similarity = 0.664
Pretty fast.

4. similarity = 0.662
Very fast and all right, I recommend.

5. similarity = 0.660
fast and safe

6. similarity = 0.639
Correct and fast!

7. similarity = 0.634
very good .Quick delivery

8. similarity = 0.631
Very good, it arrived super fast.
================================================================================
REVIEW 1024
================================================================================

Original:
Quality product

Nearest neighbors:

1. similarity = 0.862
Product of excellent quality

2. similarity = 0.862
Product of excellent quality

3. similarity = 0.849
Good quality product

4. similarity = 0.829
Good product and quality

5. similarity = 0.785
excellent quality products

6. similarity = 0.774
Product of very low quality

7. similarity = 0.750
Quality product I expected, good.

8. similarity = 0.736
very good quality product
================================================================================
REVIEW 859
================================================================================

Original:
Beautiful product, but it is a little fragile, in the photo it seemed more resistant. Delivery note 10

Nearest neighbors:

1. similarity = 0.633
Great product, I recommend the store note 10!!!

2. similarity = 0.570
The product was delivered before the deadline. Thank you for following our appeal. Note 10.

3. similarity = 0.562
I received at the time of delivery with the excellent seller of the product Note 10

4. similarity = 0.528
Excellent shop, but the product is ZERO note. I didn't even take it out of the packaging. I threw it right in the trash.

5. similarity = 0.517
great and very beautiful and it was still delivered before the date, super recommend.

6. similarity = 0.516
Magnificent....Note 10

7. similarity = 0.501
I thought it was excellent! Sure, product exactly as it is in the picture. I only recommend shortening the delivery time, I was looking forward to the merchandise.

8. similarity = 0.475
Store note 10
================================================================================
REVIEW 170
================================================================================

Original:
But the product arrived with divergent color, I bought a red came greener, very good the quality of the product but I did not like the color even pq my yesterday the kitchen are all red.

Nearest neighbors:

1. similarity = 0.564
Product came in the wrong color, bought black came greenw

2. similarity = 0.549
Product came right, but the color was changed.

3. similarity = 0.527
The product is good but came from the wrong color.

4. similarity = 0.520
The chosen product was white, and it came in green.

5. similarity = 0.490
The product arrived before the deadline. I thought it would be better, in the photo it's different, it's beautiful. What I received is very simple the color is different.

6. similarity = 0.474
The only defect, I ordered the product of the green color and came yellow.

7. similarity = 0.474
The order contains the green color and was delivered in the blue color. It was for Christmas decoration.

8. similarity = 0.467
The only problem I had was getting the wrong product, in the tax note came what I had chosen red towel, but at the time they received and opened came cream towel with brown.
================================================================================
REVIEW 900
================================================================================

Original:
I've loved the product, it's been a long time.

Nearest neighbors:

1. similarity = 0.699
I loved the product..I recommend

2. similarity = 0.691
I loved my product, I highly recommend

3. similarity = 0.673
I like the product and I recommend it great!

4. similarity = 0.665
Great product, but I haven't tried it yet.

5. similarity = 0.648
I haven't gotten the product yet, I don't have an opinion about it.

6. similarity = 0.638
I haven't tried the product yet.

7. similarity = 0.627
I like the product, very good

8. similarity = 0.622
I love the product of great quality.
================================================================================
REVIEW 1705
================================================================================

Original:
Good and timely product

Nearest neighbors:

1. similarity = 0.731
Very good product and delivery on time

2. similarity = 0.718
Good product and fast delivery.

3. similarity = 0.717
Good product and delivery before the deadline.

4. similarity = 0.711
Very good product arrived in the right time frame

5. similarity = 0.709
Great product and fast delivery before deadline

6. similarity = 0.701
Good quality product delivered within the deadline

7. similarity = 0.691
Good product and quality

8. similarity = 0.690
Quality product, delivery before the deadline. Excellent
================================================================================
REVIEW 187
================================================================================

Original:
Good product and satisfactory delivery.

Nearest neighbors:

1. similarity = 0.829
Good product and fast delivery.

2. similarity = 0.806
Very good product and delivery on time

3. similarity = 0.793
Fast delivery, good quality product.

4. similarity = 0.793
Good product and quality

5. similarity = 0.777
Good product and fast delivery!

6. similarity = 0.768
Excellent product and super fast delivery.

7. similarity = 0.765
Very efficient delivery, with quality product.

8. similarity = 0.765
The product is very good. The delivery was very fast. I just didn't like the way it came packed, the box kneaded, besides not being the product's own box. But the product itself is great.
================================================================================
REVIEW 1466
================================================================================

Original:
I love it.

Nearest neighbors:

1. similarity = 1.000
I love it.

2. similarity = 1.000
I love it.

3. similarity = 0.820
I love it!

4. similarity = 0.776
I like it.

5. similarity = 0.768
I really like it.

6. similarity = 0.687
I like it very much.

7. similarity = 0.621
I like it, very much!

8. similarity = 0.611
I loved it.
================================================================================
REVIEW 1568
================================================================================

Original:
THE PRODUCT IS OF QUALITY PESSIM. I SHOULD HAVE PLAYED ON THE DESCRIPTION Q IT WAS A REPLICA. NO CONDITIONS TO PRESENT SOMEONE WITH THAT. HORRIVABLE. PAY MORE THAN R$ 80 IN BREAKDOWN OF 1,99

Nearest neighbors:

1. similarity = 0.682
The products that sent me were replicas of what I requested. Products of bad quality!!!

2. similarity = 0.514
Product of great quality. I'd buy it again for sure.

3. similarity = 0.489
I like the watch and it looks original, but it didn't come and the packaging isn't the traditional of the case and it didn't come warranty certificate either. I'll contact the seller and the Lannister complaining

4. similarity = 0.482
incomplete product, poor quality.

5. similarity = 0.479
Product of excellent quality, I recommend because it arrived before the deadline and came straight without any defects

6. similarity = 0.474
Product of excellent quality, perfect. Responsible seller, I received the product well before the deadline. I recommend with certainty I will buy another one for my wife. I would give 10 stars if I could

7. similarity = 0.468
The product is of the highest quality, the cartridge is very good and the material resistant, INDICATED TO ALL, THIS PLACE SURPRISED ME.

8. similarity = 0.466
Product of very low quality
================================================================================
REVIEW 870
================================================================================

Original:
I need to get my product!

Nearest neighbors:

1. similarity = 0.954
I need to get my product.

2. similarity = 0.779
I want to receive the product I bought

3. similarity = 0.703
I need you to deliver the product to me.

4. similarity = 0.676
My product never arrived

5. similarity = 0.658
I didn't get my product.

6. similarity = 0.645
I just got one of the products from the order.

7. similarity = 0.629
I want my product where is it?

8. similarity = 0.619
Hello, I'm waiting for my product to be delivered.
================================================================================
REVIEW 1386
================================================================================

Original:
Product delivered in the best quality term

Nearest neighbors:

1. similarity = 0.756
Quality product, delivery as planned.

2. similarity = 0.728
Quality product, to be delivered before the deadline

3. similarity = 0.727
Quality product

4. similarity = 0.726
Quality product and serious store in delivery.

5. similarity = 0.723
Very efficient delivery, with quality product.

6. similarity = 0.707
Fast delivery. Quality product

7. similarity = 0.705
Quality product, more late in delivery.

8. similarity = 0.703
Good quality product delivered within the deadline
================================================================================
REVIEW 1048
================================================================================

Original:
It arrived well before the deadline, super well packed, worth buying.

Nearest neighbors:

1. similarity = 0.827
within the deadline, well packed, worth buying.

2. similarity = 0.786
Excellent product as expected packed very well delivery before deadline

3. similarity = 0.771
Product was delivered within the deadline, surpassing my expectations. It came well packed and without damage, despite the box crushed.

4. similarity = 0.762
It has arrived before the deadline and the merchandise is of excellent quality

5. similarity = 0.758
It was delivered well before the deadline.

6. similarity = 0.746
Delivered before the deadline all well packed

7. similarity = 0.733
Arrived before the given deadline is the product in great quality.

8. similarity = 0.730
arrived within the deadline and product of great quality

### Appendix: Aspect Candidates

The preceding exploratory and diagnostic investigation produced the following aspect candidates, which will be used later in the aspect-extraction step with an LLM.

**aspect**: a short, specific `snake_case` label for what is being evaluated.

- "overall_satisfaction"
- "product_quality"
- "product_condition_damage"
- "product_completeness"
- "product_color_accuracy"
- "product_description_accuracy"
- "product_appearance"
- "wrong_item_shipped"
- "packaging"
- "delivery_timing"
- "delivery_non_receipt"
- "price"
- "seller_contact"
- "seller_service"
- "others"

## LLM-Based Aspect Extraction

Background

This stage uses a large language model (LLM) to perform aspect-based extraction from Brazilian Portuguese e-commerce reviews. The LLM identifies the specific aspect being evaluated, based on the candidate aspects established in the previous section, the attitude toward that aspect, and, where relevant, its discourse role and concession relation. These structured evaluations are subsequently used to construct ratings for three broader categories: Product, Seller, and Delivery.

### Methodology

The procedure begins by preparing the review data and initializing the LLM with the predefined extraction prompt and response schema. Each unique, non-empty Portuguese review is then analyzed to identify evaluative spans, their specific aspects, attitudes, and discourse characteristics, with the results saved incrementally for reproducibility and recovery. The extracted results are subsequently converted into a structured aspect-level dataset and checked for invalid discourse annotations. Multiple evaluations of the same aspect within a review are then consolidated using discourse role and relation to determine their relative contribution, with opposing evaluations allowed to offset one another. Finally, overall and unassignable evaluations are excluded from the specific-aspect rating system, the remaining aspects are grouped into Product, Seller, and Delivery, and aspect-level evaluations are aggregated into category ratings on a 1–5 scale.

In [3]:
import os
from google import genai
from google.genai import types
import pandas as pd
import time
import json
from dotenv import load_dotenv

### 1. Load resources and initialize the LLM

This section prepares the review dataset and LLM.

The JSON schema constrains the structure of the LLM response. It is provided with each request to enforce a machine-readable and consistent output format.

The prompt contains the actual instructions defining what counts as evaluative content, how aspects and attitudes should be assigned, and how discourse relations should be annotated (see [prompt](../src/aspect_extraction_prompt.md) and [its design](../src/aspect_extraction_prompt_design.md)). It is stored separately from the notebook so that the exact prompt used for the analysis can be preserved and passed directly to the LLM.

In [ ]:
with open(r"../src/aspect_schema.json", "r", encoding="utf-8") as f:
    schema = json.load(f)
with open(r"../src/aspect_extraction_prompt.md", "r", encoding="utf-8") as f:
    absa_instructions = f.read()

The translated review dataset is loaded. Duplicate review texts are removed on the review content rather than the index, because `order_id` is not a reliable unique identifier for the review table. Empty review comments are also excluded because they contain no text for the LLM to analyze.

In [18]:
reviews = pd.read_csv(r"../src/olist_reviews_translated.csv", index_col='order_id', 
                        parse_dates=['review_creation_date', 'review_answer_timestamp'], 
                        date_format="%Y-%m-%d %H:%M:%S")

unique_reviews = reviews[
    reviews["review_comment_message"].notna()
    & ~reviews["review_comment_message"].duplicated()
].copy()

The Gemini client provides access to the selected generative model. Since the extraction prompt is long and remains unchanged across reviews, it is placed in Gemini's cached context and reused across requests, reducing the need to repeatedly process the same instructions.

> **API key and Gemini API tier**
>
> This notebook uses the Gemini API. Before running the code, place your own API key in a `.env` file in the project root:
>
> ```text
> GEMINI_API_KEY=your_api_key_here
> ```
>
> The `.env` file is excluded from version control and should not be uploaded to GitHub.
>
> The aspect-extraction workflow uses a cached version of the prompt/model context. Therefore, a **paid Gemini API tier** is required to run this part of the notebook with caching enabled.

In [ ]:
load_dotenv()

if not os.getenv("GEMINI_API_KEY"):
    raise RuntimeError("GEMINI_API_KEY is not set.")

client = genai.Client()
MODEL = "gemini-3.1-flash-lite"

cache = client.caches.create(
    model=MODEL,
    config=types.CreateCachedContentConfig(
        system_instruction=absa_instructions,
        ttl="36000s",  # cache lifetime; adjust if needed
    ),
)

print("Created cache:", cache.name)

Created cache: cachedContents/rwh1ipfv44j4x0dh6fpdwcx5y12fer68si1irny6

### 2. Run and persist the aspect extraction

analyze_review() sends an individual Portuguese review to Gemini and returns the structured aspect analysis, token-usage information, and the raw response. The analysis is processed incrementally and saved immediately to a JSONL file so that the long-running computation can be resumed without repeating successfully completed reviews.

In [20]:
from src.aspect_extraction import analyze_review

The analysis is computationally expensive and may be interrupted by API limits or other errors, so results are persisted after each review rather than being kept only in memory. JSONL is suitable for this purpose because new records can be appended without rewriting the existing results.

Before processing begins, previously successful records are identified from the output file. A record with error = None is considered completed, including cases where the model returns an empty extraction ({"spans": []}), since an empty extraction is a valid model response rather than an API failure. Malformed or incomplete JSONL records are ignored because they may result from an interrupted write.

The remaining reviews are then processed one at a time. `time.perf_counter()` records the elapsed time for each review, allowing the computational performance of the extraction process to be examined later.

A specific retry mechanism handles `429 RESOURCE_EXHAUSTED` errors, which indicate that the Gemini resource or quota limit has temporarily been reached. The request is paused and retried rather than being recorded as a permanent failure. Other exceptions are recorded in the JSONL output, allowing the analysis to continue with subsequent reviews.

In [21]:
# ============================================================
# 1. Load IDs that have already been successfully recorded
# ============================================================
output_file = r"../data/processed/review_analysis.jsonl"
completed_ids = set()

if os.path.exists(output_file):
    with open(output_file, "r", encoding="utf-8") as f:
        for line in f:
            try:
                record = json.loads(line)

                # Only treat successful records as completed
                if record.get("error") is None:
                    completed_ids.add(record["id"])

            except (json.JSONDecodeError, KeyError):
                # Ignore malformed/incomplete lines
                continue

print(f"Found {len(completed_ids)} completed reviews.")


# ============================================================
# 2. Select reviews that still need to be processed
# ============================================================

remaining = unique_reviews[
    ~unique_reviews.index.isin(completed_ids)
]

print(f"Remaining reviews: {len(remaining)}")


# ============================================================
# 3. Process reviews
# ============================================================

with open(output_file, "a", encoding="utf-8") as f:

    for i, (idx, row) in enumerate(remaining.iterrows(), start=1):

        review_pt = row["review_comment_message"]

        print(
            f"Processing {i}/{len(remaining)} | ID: {idx}"
        )

        start_time = time.perf_counter()

        # ----------------------------------------------------
        # Retry loop
        # ----------------------------------------------------

        while True:

            try:
                analysis, usage, response = analyze_review(review_pt, cache.name, client, schema, model=MODEL)

                # Successful request
                elapsed = time.perf_counter() - start_time

                record = {
                    # Original dataset information
                    "id": idx,
                    "review_pt": review_pt,

                    # Gemini analysis
                    "analysis": analysis,

                    # Usage / performance information
                    "input_tokens": usage["input_tokens"],
                    "output_tokens": usage["output_tokens"],
                    "cached_tokens": usage["cached_tokens"],
                    "time_seconds": elapsed,

                    # Error information
                    "error": None,
                }

                break


            except Exception as e:

                error_text = str(e)

                if "429" in error_text and "RESOURCE_EXHAUSTED" in error_text:

                    print("\n" + "=" * 80)
                    print("GEMINI 429 ERROR")
                    print(error_text)
                    print("=" * 80 + "\n")

                    # Temporary: wait before retrying
                    time.sleep(30)

                    continue



                # ------------------------------------------------
                # Any non-429 error
                # ------------------------------------------------

                elapsed = time.perf_counter() - start_time

                print(
                    f"Error for ID {idx}: {error_text}"
                )

                record = {
                    "id": idx,
                    "review_pt": review_pt,
                    "analysis": None,
                    "input_tokens": None,
                    "output_tokens": None,
                    "cached_tokens": None,
                    "time_seconds": elapsed,
                    "error": error_text,
                }

                break


        # ========================================================
        # 4. Save result immediately
        # ========================================================

        f.write(
            json.dumps(
                record,
                ensure_ascii=False
            ) + "\n"
        )

        f.flush()


        # ========================================================
        # 5. Small delay between successful requests
        # ========================================================

        time.sleep(0.5)

Found 36101 completed reviews.
Remaining reviews: 1
Processing 1/1 | ID: 30125d2cf4cec0bf9e4840def6c4e7b1
Error for ID 30125d2cf4cec0bf9e4840def6c4e7b1: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1016)

### 3. Construct the Aspect-Level Dataset

The saved LLM results are transformed into a structured DataFrame for subsequent analysis.

`load_analysis_jsonl()` reads the previously saved JSONL file and converts each line back into a Python dictionary, which is then assembled into `results_df`.

Because the LLM analysis is performed on Portuguese reviews, the JSONL file stores the Portuguese text used for extraction. The English translation is restored afterward using the Portuguese review text as the lookup key rather than the identifier, since the identifier is not unique. The English version is retained primarily to facilitate manual inspection and interpretation of the extracted results.

In [22]:
from src.aspect_extraction import load_analysis_jsonl

results = load_analysis_jsonl(output_file)
results_df = pd.DataFrame(results)

review_en_map = (
    unique_reviews
    .set_index("review_comment_message")["review_comment_en"]
)

results_df["review_en"] = results_df["review_pt"].map(review_en_map)

The original LLM output is nested because each review may contain multiple extracted spans:
```
one review
    └── spans
         ├── span 1
         ├── span 2
         └── span 3
```
For analysis, this nested structure is flattened so that each extracted evaluative span becomes one row:

> review | text | aspect | attitude | discourse_role | relation

This representation makes individual aspect evaluations easier to filter, inspect, validate, and aggregate using Pandas, which produces the main aspect-level dataset used by the subsequent validation and aggregation steps.

In [ ]:
aspect_rows = []

for _, row in results_df.iterrows():

    analysis = row["analysis"]

    if analysis is None:
        continue

    for span in analysis["spans"]:
        aspect_rows.append({
            "id": row["id"],
            "review_pt": row["review_pt"],
            "review_en": row["review_en"],
            "text": span["text"],
            "aspect": span["aspect"],
            "attitude": span["attitude"],
            "discourse_role": span["discourse_role"],
            "relation": span["relation"],
        })

aspect_df = pd.DataFrame(aspect_rows)

### 4. Validate and Correct Discourse Combinations

The LLM can occasionally generate combinations of `discourse_role` and `relation` that are individually valid enum values but logically inconsistent with the intended dependency between the two fields. These cases are isolated and manually revised based on the context of the original review.

The valid combinations are:

none       → none  
nucleus    → none  
satellite  → concession_tradeoff or concession_exclusion

In [24]:
from src.aspect_extraction import validate_discourse_relation

pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", None)
validation_df = validate_discourse_relation(aspect_df)
validation_df

,id,review_pt,review_en,text,aspect,attitude,discourse_role,relation,validation_error
22685,a77696c7b42da1121205a92ddae7b5c7,"produto não atende a sua finalidade, pois não tem o conversor de hdmi para chá.","product does not meet its purpose, because it does not have the converter of hdmi for tea.",não tem o conversor de hdmi para chá,product_completeness,negative,satellite,none,"Invalid combination: discourse_role='satellite', relation='none'"
30972,8836e9da58524060994ead4403874ad3,"Apesar de ter demorado mais do que o necessário, o ´produto chegou antes do prazo. Mas poderia ser mais rápido, já que o frete é pago. Do resto estava tudo ok.","Although it took longer than necessary, the product arrived before the deadline. But it could be faster, since the freight is paid. Of the rest everything was ok.",o frete é pago,price,negative,satellite,none,"Invalid combination: discourse_role='satellite', relation='none'"
42985,8ec58bc9d39789f8d32575cc5ce0cf0c,"O perfume é bom, tem uma fixação boa, mas não há uma grande expansão do cheiro!","The perfume is good, it has a good fixation, but there is not a great expansion of the smell!",não há uma grande expansão do cheiro,product_quality,negative,nucleus,concession_tradeoff,"Invalid combination: discourse_role='nucleus', relation='concession_tradeoff'"
48735,064df82a5ad596912cc304c6c72a42bf,"Fiz a solicitação de cancelamento do pedido e não obtive resposta da empresa. Ainda por cima consta no site como produto entregue, porém não o recebi.","I made the request to cancel the order and I did not get a reply from the company. Above all, it is listed on the website as a product delivered, but I did not receive it.",não o recebi,delivery_non_receipt,negative,nucleus,concession_tradeoff,"Invalid combination: discourse_role='nucleus', relation='concession_tradeoff'"
50699,cf0c47c42ff868bcd8e038ee2945c1b1,No site o shampoo esta como 500ml e chegou um de 300ml... Isso e propagana enganosa,On the site the shampoo is like 500ml and came a 300ml... that and deceptive propaganda,no site o shampoo esta como 500ml e chegou um de 300ml,product_description_accuracy,negative,satellite,none,"Invalid combination: discourse_role='satellite', relation='none'"
64979,9dfd36609f9bcc11f7712d98466d9aa5,no site o cartucho era original e recebi um cartucho compatível.... propaganda enganosa!!!\r\n\r\n\r\n\r\n\r\n\r\n,on the site the cartridge was original and received a compatible cartridge.... misleading propaganda!!!,no site o cartucho era original,product_description_accuracy,neutral,satellite,none,"Invalid combination: discourse_role='satellite', relation='none'"
65009,cd12238095fc7765f26477b48b9cb3b2,"Achei que a embalagem de entrega poderia ter sido de melhor qualidade. Uma caixa simples que, aparentemente, pode gerar danos ao produto. Mas a princípio o meu produto chegou em perfeito estado.","I thought the delivery package might have been of better quality, a simple box that, apparently, could cause damage to the product, but at first my product came in perfect condition.",meu produto chegou em perfeito estado,product_condition_damage,positive,nucleus,concession_tradeoff,"Invalid combination: discourse_role='nucleus', relation='concession_tradeoff'"

The purpose of this step is diagnosis rather than automatic correction. Each invalid aspect-level record is inspected separately because its intended interpretation depends on the context of the original review.

In [25]:
invalid_id = validation_df["id"]
invalid_aspect_df = aspect_df[aspect_df["id"].isin(invalid_id)]
invalid_aspect_df

,id,review_pt,review_en,text,aspect,attitude,discourse_role,relation
22684,a77696c7b42da1121205a92ddae7b5c7,"produto não atende a sua finalidade, pois não tem o conversor de hdmi para chá.","product does not meet its purpose, because it does not have the converter of hdmi for tea.",produto não atende a sua finalidade,product_quality,negative,nucleus,none
22685,a77696c7b42da1121205a92ddae7b5c7,"produto não atende a sua finalidade, pois não tem o conversor de hdmi para chá.","product does not meet its purpose, because it does not have the converter of hdmi for tea.",não tem o conversor de hdmi para chá,product_completeness,negative,satellite,none
30969,8836e9da58524060994ead4403874ad3,"Apesar de ter demorado mais do que o necessário, o ´produto chegou antes do prazo. Mas poderia ser mais rápido, já que o frete é pago. Do resto estava tudo ok.","Although it took longer than necessary, the product arrived before the deadline. But it could be faster, since the freight is paid. Of the rest everything was ok.",ter demorado mais do que o necessário,delivery_timing,negative,satellite,concession_tradeoff
30970,8836e9da58524060994ead4403874ad3,"Apesar de ter demorado mais do que o necessário, o ´produto chegou antes do prazo. Mas poderia ser mais rápido, já que o frete é pago. Do resto estava tudo ok.","Although it took longer than necessary, the product arrived before the deadline. But it could be faster, since the freight is paid. Of the rest everything was ok.",o produto chegou antes do prazo,delivery_timing,positive,nucleus,none
30971,8836e9da58524060994ead4403874ad3,"Apesar de ter demorado mais do que o necessário, o ´produto chegou antes do prazo. Mas poderia ser mais rápido, já que o frete é pago. Do resto estava tudo ok.","Although it took longer than necessary, the product arrived before the deadline. But it could be faster, since the freight is paid. Of the rest everything was ok.",poderia ser mais rápido,delivery_timing,negative,nucleus,none
30972,8836e9da58524060994ead4403874ad3,"Apesar de ter demorado mais do que o necessário, o ´produto chegou antes do prazo. Mas poderia ser mais rápido, já que o frete é pago. Do resto estava tudo ok.","Although it took longer than necessary, the product arrived before the deadline. But it could be faster, since the freight is paid. Of the rest everything was ok.",o frete é pago,price,negative,satellite,none
30973,8836e9da58524060994ead4403874ad3,"Apesar de ter demorado mais do que o necessário, o ´produto chegou antes do prazo. Mas poderia ser mais rápido, já que o frete é pago. Do resto estava tudo ok.","Although it took longer than necessary, the product arrived before the deadline. But it could be faster, since the freight is paid. Of the rest everything was ok.",estava tudo ok,overall_satisfaction,positive,none,none
42983,8ec58bc9d39789f8d32575cc5ce0cf0c,"O perfume é bom, tem uma fixação boa, mas não há uma grande expansão do cheiro!","The perfume is good, it has a good fixation, but there is not a great expansion of the smell!",O perfume é bom,product_quality,positive,none,none
42984,8ec58bc9d39789f8d32575cc5ce0cf0c,"O perfume é bom, tem uma fixação boa, mas não há uma grande expansão do cheiro!","The perfume is good, it has a good fixation, but there is not a great expansion of the smell!",tem uma fixação boa,product_quality,positive,none,none
42985,8ec58bc9d39789f8d32575cc5ce0cf0c,"O perfume é bom, tem uma fixação boa, mas não há uma grande expansão do cheiro!","The perfume is good, it has a good fixation, but there is not a great expansion of the smell!",não há uma grande expansão do cheiro,product_quality,negative,nucleus,concession_tradeoff
48734,064df82a5ad596912cc304c6c72a42bf,"Fiz a solicitação de cancelamento do pedido e não obtive resposta da empresa. Ainda por cima consta no site como produto entregue, porém não o recebi.","I made the request to cancel the order and I did not get a reply from the company. Above all, it is listed on the website as a product delivered, but I did not receive it.",não obtive resposta da empresa,seller_service,negative,none,none
48735,064df82a5ad596912cc304c6c72a42bf,"Fiz a solicitação de cancelamento do pedido e não obtive resposta da empresa. Ainda por cima consta no site como produto entregue, porém não o recebi.","I made the request to cancel the order and I did not get a reply from the company. Above all, it is listed on the website as a product delivered, but I did not receive it.",não o recebi,delivery_non_receipt,negative,nucleus,concession_tradeoff
50699,cf0c47c42ff868bcd8e038ee2945c1b1,No site o shampoo esta como 500ml e chegou um de 300ml... Isso e propagana enganosa,On the site the shampoo is like 500ml and came a 300ml... that and deceptive propaganda,no site o shampoo esta como 500ml e chegou um de 300ml,product_description_accuracy,negative,satellite,none
50700,cf0c47c42ff868bcd8e038ee2945c1b1,No site o shampoo esta como 500ml e chegou um de 300ml... Isso e propagana enganosa,On the site the shampoo is like 500ml and came a 300ml... that and deceptive propaganda,propagana enganosa,product_description_accuracy,negative,nucleus,none
64979,9dfd36609f9bcc11f7712d98466d9aa5,no site o cartucho era original e recebi um cartucho compatível.... propaganda enganosa!!!\r\n\r\n\r\n\r\n\r\n\r\n,on the site the cartridge was original and received a compatible cartridge.... misleading propaganda!!!,no site o cartucho era original,product_description_accuracy,neutral,satellite,none
64980,9dfd36609f9bcc11f7712d98466d9aa5,no site o cartucho era original e recebi um cartucho compatível.... propaganda enganosa!!!\r\n\r\n\r\n\r\n\r\n\r\n,on the site the cartridge was original and received a compatible cartridge.... misleading propaganda!!!,recebi um cartucho compatível,wrong_item_shipped,negative,nucleus,none
64981,9dfd36609f9bcc11f7712d98466d9aa5,no site o cartucho era original e recebi um cartucho compatível.... propaganda enganosa!!!\r\n\r\n\r\n\r\n\r\n\r\n,on the site the cartridge was original and received a compatible cartridge.... misleading propaganda!!!,propaganda enganosa,product_description_accuracy,negative,none,none
65007,cd12238095fc7765f26477b48b9cb3b2,"Achei que a embalagem de entrega poderia ter sido de melhor qualidade. Uma caixa simples que, aparentemente, pode gerar danos ao produto. Mas a princípio o meu produto chegou em perfeito estado.","I thought the delivery package might have been of better quality, a simple box that, apparently, could cause damage to the product, but at first my product came in perfect condition.",a embalagem de entrega poderia ter sido de melhor qualidade,packaging,negative,none,none
65008,cd12238095fc7765f26477b48b9cb3b2,"Achei que a embalagem de entrega poderia ter sido de melhor qualidade. Uma caixa simples que, aparentemente, pode gerar danos ao produto. Mas a princípio o meu produto chegou em perfeito estado.","I thought the delivery package might have been of better quality, a simple box that, apparently, could cause damage to the product, but at first my product came in perfect condition.","caixa simples que, aparentemente, pode gerar danos ao produto",packaging,negative,none,none
65009,cd12238095fc7765f26477b48b9cb3b2,"Achei que a embalagem de entrega poderia ter sido de melhor qualidade. Uma caixa simples que, aparentemente, pode gerar danos ao produto. Mas a princípio o meu produto chegou em perfeito estado.","I thought the delivery package might have been of better quality, a simple box that, apparently, could cause damage to the product, but at first my product came in perfect condition.",meu produto chegou em perfeito estado,product_condition_damage,positive,nucleus,concession_tradeoff

For cases where `discourse_role == "nucleus"`, the relation can be safely corrected to `"none"` because concession relations apply to the subordinate satellite rather than the nucleus.

For cases where `discourse_role == "satellite"` and `relation == "none"`, inspection showed that these cases were associated with causal or explanatory clauses that had been extracted as evaluative spans. Although these clauses contain genuine evaluative content, retaining both the main evaluative statement and its causal explanation would cause the same issue to be represented twice when the aspect evaluations are later mapped to the broader Product, Seller, and Delivery categories. These subordinate reason spans are therefore excluded from the subsequent aggregation.

In [26]:
invalid_aspect_df.loc[invalid_aspect_df["discourse_role"] == "nucleus", "relation"] = 'none'
invalid_aspect_df = invalid_aspect_df[
                ~((invalid_aspect_df["discourse_role"] == "satellite") & 
                (invalid_aspect_df["relation"] == "none")) ]
aspect_df[aspect_df["id"].isin(invalid_id)] = invalid_aspect_df

C:\Users\19148\AppData\Local\Temp\ipykernel_22336\784987126.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  invalid_aspect_df.loc[invalid_aspect_df["discourse_role"] == "nucleus", "relation"] = 'none'

### 5. Aggregate Aspect Evaluations

Multiple evaluations of the same specific aspect within a review are consolidated into a single aspect-level evaluation. Discourse structure is converted into an aggregation weight so that independent or nucleus evaluations contribute more strongly than concessive evaluations. Contradictory positive and negative evaluations are combined using their weighted net effect.

`aggregate_aspect_df()` performs this consolidation. The discourse hierarchy is:
$$
\mathrm{none/nucleus}>\mathrm{concession\_tradeoff}>\mathrm{concession\_exclusion}
$$
with corresponding weights:
$$
2,\qquad 1,\qquad 0.
$$

For evaluations with opposing attitudes toward the same aspect, the weights are treated as signed evidence. The resulting net weight is:
$$
\mathrm{net\ weight}=\mathrm{positive\ weight}−\mathrm{negative\ weight}.
$$
Thus, equal positive and negative evidence cancels out, while a positive or negative net weight determines the final attitude. This produces at most one final evaluation for each specific aspect within a review and prevents multiple contradictory evaluations from being carried independently into the subsequent category-level rating.

In [27]:
from src.aspect_extraction import aggregate_aspect_df

aggregated_df = aggregate_aspect_df(aspect_df)

### 6. Remove Overall Satisfaction

When a review contains specific aspect evaluations, `overall_satisfaction` is removed from the aspect-rating calculation. It represents the reviewer's overall assessment and is conceptually closer to the customer's original overall rating than to any of the three substantive dimensions being constructed.

If `overall_satisfaction` is the only evaluation in a review, it is retained for possible later comparison with the original customer rating. This prevents an overall evaluation from being incorrectly incorporated into the Product, Seller, or Delivery categories.

In [28]:
from src.aspect_extraction import remove_overall_satisfaction

aggregated_df = remove_overall_satisfaction(aggregated_df)

### 7. Calculate Category Score

Specific aspect evaluations are converted into 1–5 ratings for three broader dimensions of the e-commerce experience: **Product**, **Seller**, and **Delivery**.

Each aspect first receives an aspect-level score based on its attitude and discourse weight. The current discourse weights are:
$$
w = 
\begin{cases}
0 & \mathrm{concession\_exclusion}\\
1 & \mathrm{concession\_tradeoff} \\
2 & \mathrm{none/nucleus​}
\end{cases}
$$

Using a neutral baseline of 3, the aspect score is:
$$
S_i = 3 + w_is_i
$$
where $s_i=1$ for a positive evaluation, $0$ for a neutral evaluation, and $−1$ for a negative evaluation.

calculate_category_scores() performs the final transformation from specific aspects to the three broad dimensions:

Product
Seller
Delivery


Each specific aspect first receives an aspect-level score based on its attitude and discourse weight.

The current discourse weights are:
$$
w = 
\begin{cases}
0 & \mathrm{concession\_exclusion}\\
1 & \mathrm{concession\_tradeoff} \\
2 & \mathrm{none/nucleus​}
\end{cases}
$$
Using a neutral baseline of 3, the aspect score is:
$$
S_i = 3 + w_is_i
$$
where $s_i=1$ for a positive evaluation, $0$ for a neutral evaluation, and $−1$ for a negative evaluation.


The aspect scores belonging to the same category within a review are then averaged. The mapping is based on **whose performance/responsibility this evaluation primarily concerns**, rather than simply on the wording of the aspect label.

The current mapping is:

**Product**
- "product_quality"
- "product_condition_damage"
- "product_color_accuracy"
- "product_appearance"

**Seller**
- "product_completeness"
- "product_description_accuracy"
- "wrong_item_shipped"
- "price"
- "seller_contact"
- "seller_service"

**Delivery**
- "packaging"
- "delivery_timing"
- "delivery_non_receipt"

"others" and "overall_satisfaction" are excluded because they cannot be meaningfully incorporated into these three categories. A category that is not mentioned receives no rating rather than an artificial neutral score.

In [29]:
from src.aspect_extraction import calculate_category_scores

score_df = calculate_category_scores(aggregated_df)
score_df.head()

,review_pt,review_en,category,score
0,"\r\n\r\n\r\nDe todo o pedido feito no site, este foi o que mais demorou para entregar!!!","Of all the request made on the website, this was the most time to deliver!!!",delivery,1.0
1,\r\n\r\nHouve um impedimento relatado em outro e-mail justificando o atraso da entrega do produto .\r\nNesse momento ainda não recebi a compra.\r\nAguardo informações \r\nPatrícia,There was an impediment reported in another email justifying the delay of delivery of the product. At this time I have not yet received the purchase. I await information Patrícia,delivery,1.0
2,"\r\nApesar de de ser entregue antes do previsto, prazo de entrega é muito longo.Enfim, mais por causa dos Correios mesmo que é um lixo. Tirando isso produto em perfeito estado. Recomendo!","Despite being delivered ahead of schedule, delivery time is very long. Anyway, more because of the Post Offices even it is a garbage. Apart from this product in perfect condition. I recommend!",delivery,2.0
3,"\r\nApesar de de ser entregue antes do previsto, prazo de entrega é muito longo.Enfim, mais por causa dos Correios mesmo que é um lixo. Tirando isso produto em perfeito estado. Recomendo!","Despite being delivered ahead of schedule, delivery time is very long. Anyway, more because of the Post Offices even it is a garbage. Apart from this product in perfect condition. I recommend!",product,5.0
4,\r\nComprei um produto e entregaram outro difetente do que pedi..... E mais solicitei a devolucao ou troca e ate agora nada.... Estam se fazendo de dezentendidos...\r\nE fazer pouco caso do cliente ne..,I bought a product and they delivered another defect than I asked... and the more I asked for the return or exchange and until now nothing... they're making up their minds... and not paying any attention to the client.,seller,1.0

In [48]:
score_df.groupby("category")["score"].describe()

            count      mean       std  min  25%  50%  75%  max
category
delivery  18582.0  3.609389  1.849609  1.0  1.0  5.0  5.0  5.0
product   12883.0  3.865585  1.723366  1.0  2.0  5.0  5.0  5.0
seller    14296.0  2.831462  1.933615  1.0  1.0  1.0  5.0  5.0

In [ ]:
score_df.to_csv(
    r"../data/processed/olist_categorized_score.csv",
    index=False
)

## Summary and Next Steps

**Summary**

This notebook develops the review-based inputs needed to construct ratings for the Product, Seller, and Delivery dimensions. It first uses sentence embeddings and nearest-neighbor inspection to identify recurring topics and manually define a set of candidate aspects. It then uses an LLM to extract these aspects and their associated evaluations from the reviews, providing the information needed to calculate ratings for the three dimensions.

**Next Steps**

The resulting Product, Seller, and Delivery ratings provide the basis for the next stage of the analysis. The next notebook will aggregate these ratings and examine the resulting performance across different aspects of the purchasing experience.